---
- name: get some info
  ec2_vpc_net_info:
    region: "{{ ec2_region }}"
  register: all_the_info
  connection: local
  delegate_to: localhost
  run_once: true

- name: how many vpc?
  debug:
    msg: "There are {{ all_the_info.vpcs|length }} VPCs"

- name: install apache
  become: yes
  yum:
    name: httpd
    state: present

- name: change apache to specified port
  become: yes
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: 'Listen {{web_port}}'

- name: Set nis_enabled flag on and keep it persistent across reboots
  become: yes
  seboolean:
    name: nis_enabled
    state: yes
    persistent: yes

- name: start httpd
  become: yes
  service:
    name: httpd
    state: started

- name: create HTML report
  become: yes
  template:
    src: template.j2
    dest: "{{ file_path }}/index.html"

- name: copy CSS over
  become: yes
  copy:
    src: "css"
    dest: "{{ file_path }}"
    directory_mode: true

- name: copy image over
  become: yes
  copy:
    src: "webpage_logo.png"
    dest: "{{ file_path }}"
    directory_mode: true

- name: copy image over
  become: yes
  copy:
    src: "ocp_logo.png"
    dest: "{{ file_path }}"
    directory_mode: true

- name: display link to inventory report
  debug:
    msg: "Please go to http://{{ansible_host}}:{{web_port}}"
